-- ============================================
-- Event Entries Table (Random Box Participation)
-- ============================================

create table if not exists app_event_entries (
  id bigint generated by default as identity primary key,
  event_key text not null,
  employee_id text not null,
  nickname text,
  result text not null,
  is_winner boolean default false,
  box_index integer,
  created_at timestamptz default now()
);

create unique index if not exists app_event_entries_unique
  on app_event_entries (event_key, employee_id);

alter table app_event_entries enable row level security;

drop policy if exists "Enable all access for app_event_entries" on app_event_entries;
drop policy if exists "app_event_entries_read_authenticated" on app_event_entries;
drop policy if exists "app_event_entries_insert_authenticated" on app_event_entries;

create policy "app_event_entries_read_authenticated" on app_event_entries
  for select to authenticated using (true);

create policy "app_event_entries_insert_authenticated" on app_event_entries
  for insert to authenticated with check (true);
