-- ============================================
-- Space D - Attendance Frequency Logs
-- ============================================
-- 사용자 출/퇴근 버튼 시도 시각(requested_at)부터
-- 감지 성공/실패/취소 이력까지 모두 저장하는 로그 테이블입니다.
-- Supabase SQL Editor에서 실행하세요.

create table if not exists app_attendance_logs (
  id bigint generated by default as identity primary key,
  client_request_id text not null unique,
  user_id text,
  employee_id text not null,
  nickname text not null,
  status text not null default 'requested'
    check (status in ('requested', 'listening', 'success', 'failed', 'cancelled')),
  action_type text
    check (action_type in ('checkIn', 'checkOut')),
  action_label text,
  matched_target_frequency integer,
  detected_frequency numeric(8, 1),
  sample_rate integer,
  peak_decibel numeric(6, 1),
  requested_at timestamptz not null default now(),
  detected_at timestamptz,
  closed_at timestamptz,
  failure_reason text,
  source text not null default 'frequency-web',
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_attendance_logs_employee_requested_idx
  on app_attendance_logs (employee_id, requested_at desc);

create index if not exists app_attendance_logs_status_requested_idx
  on app_attendance_logs (status, requested_at desc);

create index if not exists app_attendance_logs_action_detected_idx
  on app_attendance_logs (action_type, detected_at desc);

alter table app_attendance_logs enable row level security;

drop policy if exists "app_attendance_logs_read_all" on app_attendance_logs;
drop policy if exists "app_attendance_logs_insert_all" on app_attendance_logs;
drop policy if exists "app_attendance_logs_update_all" on app_attendance_logs;

create policy "app_attendance_logs_read_all"
  on app_attendance_logs for select
  using (true);

create policy "app_attendance_logs_insert_all"
  on app_attendance_logs for insert
  with check (true);

create policy "app_attendance_logs_update_all"
  on app_attendance_logs for update
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update on table app_attendance_logs to anon, authenticated, service_role;
grant usage, select on sequence app_attendance_logs_id_seq to anon, authenticated, service_role;

-- --------------------------------------------
-- 확인용 쿼리 예시
-- --------------------------------------------
-- select *
-- from app_attendance_logs
-- order by requested_at desc
-- limit 30;

-- select
--   employee_id,
--   nickname,
--   count(*) as total_attempts,
--   count(*) filter (where status = 'success') as success_count,
--   count(*) filter (where status = 'failed') as failed_count,
--   count(*) filter (where status = 'cancelled') as cancelled_count,
--   count(*) filter (where action_type = 'checkIn' and status = 'success') as check_in_count,
--   count(*) filter (where action_type = 'checkOut' and status = 'success') as check_out_count,
--   max(requested_at) as last_requested_at
-- from app_attendance_logs
-- group by employee_id, nickname
-- order by last_requested_at desc;
