-- ============================================
-- Event Entries Table (Random Box Participation)
-- ============================================

create table if not exists app_event_entries (
  id bigint generated by default as identity primary key,
  event_key text not null,
  employee_id text not null,
  nickname text,
  result text not null,
  is_winner boolean default false,
  box_index integer,
  created_at timestamptz default now()
);

create unique index if not exists app_event_entries_unique
  on app_event_entries (event_key, employee_id);

alter table app_event_entries enable row level security;

create policy "Enable all access for app_event_entries" on app_event_entries
  for all using (true) with check (true);
