-- ============================================
-- Space D - Lunch Picker Menus
-- ============================================
-- Supabase SQL Editor에서 실행하세요.
-- 메인 점심 슬롯에 사용할 메뉴 마스터 테이블입니다.

create table if not exists app_lunch_menu_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  emoji text not null default '🍽️',
  menu_tag text not null default '',
  is_cafeteria boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists app_lunch_menu_items_single_cafeteria_idx
  on app_lunch_menu_items (is_cafeteria)
  where is_cafeteria = true;

create index if not exists app_lunch_menu_items_active_idx
  on app_lunch_menu_items (is_active, is_cafeteria desc, name);

insert into app_lunch_menu_items (name, emoji, menu_tag, is_cafeteria, is_active)
values ('25층 구내식당', '🏢', '직원 할인 적용', true, true)
on conflict (name) do update
set
  emoji = excluded.emoji,
  menu_tag = excluded.menu_tag,
  is_cafeteria = true,
  is_active = true,
  updated_at = now();

alter table app_lunch_menu_items enable row level security;

drop policy if exists "app_lunch_menu_items_read_all" on app_lunch_menu_items;
drop policy if exists "app_lunch_menu_items_insert_authenticated" on app_lunch_menu_items;
drop policy if exists "app_lunch_menu_items_update_authenticated" on app_lunch_menu_items;
drop policy if exists "app_lunch_menu_items_delete_authenticated" on app_lunch_menu_items;

create policy "app_lunch_menu_items_read_all"
  on app_lunch_menu_items for select
  using (true);

create policy "app_lunch_menu_items_insert_authenticated"
  on app_lunch_menu_items for insert
  with check (true);

create policy "app_lunch_menu_items_update_authenticated"
  on app_lunch_menu_items for update
  using (true)
  with check (true);

create policy "app_lunch_menu_items_delete_authenticated"
  on app_lunch_menu_items for delete
  using (true);

-- --------------------------------------------
-- 관리자 등록 예시
-- --------------------------------------------
-- insert into app_lunch_menu_items (name, emoji, menu_tag)
-- values ('순도리', '🍖', '한식 • 순대국밥');

-- --------------------------------------------
-- 활성 메뉴 조회 예시
-- --------------------------------------------
-- select id, name, emoji, menu_tag, is_cafeteria, is_active
-- from app_lunch_menu_items
-- where is_active = true
-- order by is_cafeteria desc, name asc;

-- --------------------------------------------
-- 슬롯 후보 5개 조회 예시
-- 1) 25층 구내식당은 항상 포함
-- 2) 나머지 활성 메뉴 중 랜덤 4개
-- 3) 실제 당첨 10% 보정은 프론트에서 적용
-- --------------------------------------------
-- with cafeteria as (
--   select id, name, emoji, menu_tag, is_cafeteria, is_active
--   from app_lunch_menu_items
--   where is_active = true and is_cafeteria = true
--   limit 1
-- ),
-- others as (
--   select id, name, emoji, menu_tag, is_cafeteria, is_active
--   from app_lunch_menu_items
--   where is_active = true and coalesce(is_cafeteria, false) = false
--   order by random()
--   limit 4
-- )
-- select * from cafeteria
-- union all
-- select * from others;
