-- ============================================
-- Space D - Capsule Escape Game
-- ============================================
-- Supabase 대시보드 > SQL Editor에서 실행하세요

create extension if not exists pgcrypto;

create table if not exists public.app_race_rooms (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  host_employee_id text not null,
  host_nickname text not null,
  status text not null default 'waiting'
    check (status in ('waiting', 'running', 'finished')),
  race_seed integer,
  duration_ms integer,
  slow_start_ms integer,
  started_at timestamptz,
  finished_at timestamptz,
  winner_employee_id text,
  results jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_race_participants (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.app_race_rooms(id) on delete cascade,
  employee_id text not null,
  nickname text not null,
  lane integer not null check (lane >= 0 and lane < 8),
  horse_name text not null,
  color text not null,
  joined_at timestamptz not null default now(),
  unique (room_id, employee_id),
  unique (room_id, lane)
);

create table if not exists public.app_race_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.app_race_rooms(id) on delete cascade,
  employee_id text not null,
  nickname text not null,
  message text not null check (char_length(message) <= 160),
  created_at timestamptz not null default now()
);

create index if not exists app_race_rooms_status_created_idx
  on public.app_race_rooms(status, created_at desc);

create index if not exists app_race_participants_room_lane_idx
  on public.app_race_participants(room_id, lane);

create index if not exists app_race_messages_room_created_idx
  on public.app_race_messages(room_id, created_at);

alter table public.app_race_rooms enable row level security;
alter table public.app_race_participants enable row level security;
alter table public.app_race_messages enable row level security;

drop policy if exists "app_race_rooms_read_all" on public.app_race_rooms;
drop policy if exists "app_race_rooms_insert_all" on public.app_race_rooms;
drop policy if exists "app_race_rooms_update_all" on public.app_race_rooms;
drop policy if exists "app_race_participants_read_all" on public.app_race_participants;
drop policy if exists "app_race_participants_insert_all" on public.app_race_participants;
drop policy if exists "app_race_messages_read_all" on public.app_race_messages;
drop policy if exists "app_race_messages_insert_all" on public.app_race_messages;

create policy "app_race_rooms_read_all"
  on public.app_race_rooms for select
  using (true);

create policy "app_race_rooms_insert_all"
  on public.app_race_rooms for insert
  with check (true);

create policy "app_race_rooms_update_all"
  on public.app_race_rooms for update
  using (true)
  with check (true);

create policy "app_race_participants_read_all"
  on public.app_race_participants for select
  using (true);

create policy "app_race_participants_insert_all"
  on public.app_race_participants for insert
  with check (true);

create policy "app_race_messages_read_all"
  on public.app_race_messages for select
  using (true);

create policy "app_race_messages_insert_all"
  on public.app_race_messages for insert
  with check (true);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'app_race_rooms'
    ) then
      alter publication supabase_realtime add table public.app_race_rooms;
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'app_race_participants'
    ) then
      alter publication supabase_realtime add table public.app_race_participants;
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'app_race_messages'
    ) then
      alter publication supabase_realtime add table public.app_race_messages;
    end if;
  end if;
end $$;
