-- ============================================
-- Space D - Quick Votes (칭찬하기 / 점심 투표 / 커피 투표)
-- ============================================
-- Supabase 대시보드 > SQL Editor에서 실행하세요

-- 1. quick_votes 테이블 생성
create table if not exists quick_votes (
  id bigint generated by default as identity primary key,
  vote_type text not null,      -- 'praise' | 'lunch' | 'coffee'
  option_key text not null,     -- 투표 항목 key (employee_id 또는 메뉴 key)
  option_label text,            -- 표시 이름
  employee_id text not null,    -- 투표한 사람
  vote_date text not null,      -- 'YYYY-MM-DD' (일별 리셋)
  created_at timestamptz default now()
);

-- 2. 같은 날 같은 타입에서 1인 1표 제약
create unique index if not exists quick_votes_unique
  on quick_votes (vote_type, employee_id, vote_date);

-- 3. RLS 활성화
alter table quick_votes enable row level security;

-- 4. 모든 인증 사용자 읽기 허용
create policy "quick_votes_read_all"
  on quick_votes for select
  using (true);

-- 5. 인증된 사용자 투표 추가
create policy "quick_votes_insert_authenticated"
  on quick_votes for insert
  with check (auth.role() = 'authenticated');

-- 6. 본인 투표 삭제 (취소)
create policy "quick_votes_delete_own"
  on quick_votes for delete
  using (auth.uid()::text = employee_id);

-- 7. 성능을 위한 인덱스
create index if not exists quick_votes_type_date_idx
  on quick_votes (vote_type, vote_date);
