-- ============================================
-- Coffee Time Random Groups
-- ============================================

create table if not exists app_coffee_time_events (
  id uuid primary key default gen_random_uuid(),
  title text not null default '커피타임',
  status text not null default 'published',
  fixed_employee_ids text[] not null default '{}'::text[],
  start_date date,
  participant_count integer not null default 0,
  group_count integer not null default 0,
  draw_hash text,
  created_by text,
  created_at timestamptz default now(),
  published_at timestamptz default now()
);

create table if not exists app_coffee_time_members (
  id bigint generated by default as identity primary key,
  event_id uuid not null references app_coffee_time_events(id) on delete cascade,
  employee_id text not null,
  nickname text,
  profile_icon_url text,
  role text not null default 'participant',
  created_at timestamptz default now(),
  unique (event_id, employee_id)
);

create table if not exists app_coffee_time_groups (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references app_coffee_time_events(id) on delete cascade,
  group_no integer not null,
  name text,
  assigned_date date,
  created_at timestamptz default now(),
  unique (event_id, group_no)
);

alter table app_coffee_time_events
  add column if not exists start_date date;

alter table app_coffee_time_groups
  add column if not exists assigned_date date;

create table if not exists app_coffee_time_group_members (
  id bigint generated by default as identity primary key,
  event_id uuid not null references app_coffee_time_events(id) on delete cascade,
  group_id uuid not null references app_coffee_time_groups(id) on delete cascade,
  employee_id text not null,
  role text not null default 'random',
  created_at timestamptz default now(),
  unique (group_id, employee_id)
);

alter table app_coffee_time_events enable row level security;
alter table app_coffee_time_members enable row level security;
alter table app_coffee_time_groups enable row level security;
alter table app_coffee_time_group_members enable row level security;

drop policy if exists "app_coffee_time_events_read_authenticated" on app_coffee_time_events;
drop policy if exists "app_coffee_time_events_write_authenticated" on app_coffee_time_events;
drop policy if exists "app_coffee_time_events_read_all" on app_coffee_time_events;
drop policy if exists "app_coffee_time_events_write_all" on app_coffee_time_events;
drop policy if exists "app_coffee_time_members_read_authenticated" on app_coffee_time_members;
drop policy if exists "app_coffee_time_members_write_authenticated" on app_coffee_time_members;
drop policy if exists "app_coffee_time_members_read_all" on app_coffee_time_members;
drop policy if exists "app_coffee_time_members_write_all" on app_coffee_time_members;
drop policy if exists "app_coffee_time_groups_read_authenticated" on app_coffee_time_groups;
drop policy if exists "app_coffee_time_groups_write_authenticated" on app_coffee_time_groups;
drop policy if exists "app_coffee_time_groups_read_all" on app_coffee_time_groups;
drop policy if exists "app_coffee_time_groups_write_all" on app_coffee_time_groups;
drop policy if exists "app_coffee_time_group_members_read_authenticated" on app_coffee_time_group_members;
drop policy if exists "app_coffee_time_group_members_write_authenticated" on app_coffee_time_group_members;
drop policy if exists "app_coffee_time_group_members_read_all" on app_coffee_time_group_members;
drop policy if exists "app_coffee_time_group_members_write_all" on app_coffee_time_group_members;

create policy "app_coffee_time_events_read_all" on app_coffee_time_events
  for select using (true);

create policy "app_coffee_time_events_write_all" on app_coffee_time_events
  for all using (true) with check (true);

create policy "app_coffee_time_members_read_all" on app_coffee_time_members
  for select using (true);

create policy "app_coffee_time_members_write_all" on app_coffee_time_members
  for all using (true) with check (true);

create policy "app_coffee_time_groups_read_all" on app_coffee_time_groups
  for select using (true);

create policy "app_coffee_time_groups_write_all" on app_coffee_time_groups
  for all using (true) with check (true);

create policy "app_coffee_time_group_members_read_all" on app_coffee_time_group_members
  for select using (true);

create policy "app_coffee_time_group_members_write_all" on app_coffee_time_group_members
  for all using (true) with check (true);
